[package]
name = "bme280"
version = "0.1.0"
authors = ["Alex M. <alexmgit@protonmail.com>"]
edition = "2018"
repository = "https://github.com/newAM/bme280-rs"
license = "MIT"
description = "Driver for the Bosch BME280."
readme = "README.md"
keywords = ["i2c", "driver", "embedded-hal-driver", "bosch", "bme280"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/newAM/bme280-rs"

[badges]
maintenance = { status = "experimental" }

[dependencies]
embedded-hal = "~0.2.4"

[dev-dependencies]
embedded-hal-mock = "~0.7.2"
ftd2xx-embedded-hal = "~0.8.0"
