[package]
name = "bme280-multibus"
version = "0.2.0"
authors = ["Alex Martens <alexmgit@protonmail.com>"]
edition = "2021"
rust-version = "1.56"  # Update MSRV in CI
repository = "https://github.com/newAM/bme280-multibus"
license = "MIT"
description = "BME280 driver with support for SPI and I2C"
readme = "README.md"
keywords = ["i2c", "driver", "embedded-hal-driver", "bosch", "bme280"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/newAM/bme280-multibus"

[dependencies]
embedded-hal = "0.2"

[dev-dependencies]
embedded-hal-mock = "0.8"
ftd2xx-embedded-hal = "0.9"
